// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/rpc.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("protocol/rpc.proto", fileDescriptor_13c0112e17e3b459) }

var fileDescriptor_13c0112e17e3b459 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2f, 0x2a, 0x48, 0xd6, 0x03, 0x73, 0x84, 0x38, 0x60, 0x62, 0x52,
	0xe2, 0x70, 0xd9, 0x94, 0xfc, 0xf2, 0xbc, 0x9c, 0xfc, 0xc4, 0x14, 0x88, 0x12, 0x29, 0x61, 0xb8,
	0x44, 0x71, 0x65, 0x1e, 0x54, 0x9f, 0x51, 0x2f, 0x23, 0x17, 0x77, 0x70, 0x65, 0x5e, 0x72, 0x70,
	0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x2b, 0x17, 0x87, 0x0b, 0x54, 0x9b, 0x90, 0xa4, 0x1e,
	0x4c, 0x87, 0x1e, 0x4c, 0x2c, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x4a, 0x0a, 0x9b, 0x54,
	0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x12, 0x83, 0x01, 0xa3, 0x90, 0x39, 0x17, 0x0b, 0xc8, 0x54,
	0x21, 0x51, 0x84, 0x3a, 0x10, 0x1f, 0xa6, 0x5d, 0x0c, 0x5d, 0x18, 0xa6, 0x35, 0x89, 0x0d, 0x2c,
	0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x9b, 0x12, 0xe5, 0xe4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SyncServiceClient interface {
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (SyncService_DownloadClient, error)
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type syncServiceClient struct {
	cc *grpc.ClientConn
}

func NewSyncServiceClient(cc *grpc.ClientConn) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (SyncService_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SyncService_serviceDesc.Streams[0], "/protocol.SyncService/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &syncServiceDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SyncService_DownloadClient interface {
	Recv() (*DownloadResponse, error)
	grpc.ClientStream
}

type syncServiceDownloadClient struct {
	grpc.ClientStream
}

func (x *syncServiceDownloadClient) Recv() (*DownloadResponse, error) {
	m := new(DownloadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *syncServiceClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, "/protocol.SyncService/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServiceServer is the server API for SyncService service.
type SyncServiceServer interface {
	Download(*DownloadRequest, SyncService_DownloadServer) error
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
}

func RegisterSyncServiceServer(s *grpc.Server, srv SyncServiceServer) {
	s.RegisterService(&_SyncService_serviceDesc, srv)
}

func _SyncService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncServiceServer).Download(m, &syncServiceDownloadServer{stream})
}

type SyncService_DownloadServer interface {
	Send(*DownloadResponse) error
	grpc.ServerStream
}

type syncServiceDownloadServer struct {
	grpc.ServerStream
}

func (x *syncServiceDownloadServer) Send(m *DownloadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SyncService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.SyncService/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SyncService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _SyncService_Sync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _SyncService_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocol/rpc.proto",
}
