// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/sync.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_Normal    Type = 0
	Type_Directory Type = 1
	Type_Symlink   Type = 2
)

var Type_name = map[int32]string{
	0: "Normal",
	1: "Directory",
	2: "Symlink",
}

var Type_value = map[string]int32{
	"Normal":    0,
	"Directory": 1,
	"Symlink":   2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b7183a11194efb25, []int{0}
}

type File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Checksum             string   `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Type                 Type     `protobuf:"varint,4,opt,name=type,proto3,enum=protocol.Type" json:"type,omitempty"`
	Symlink              string   `protobuf:"bytes,5,opt,name=symlink,proto3" json:"symlink,omitempty"`
	Mode                 uint32   `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid                  uint32   `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint32   `protobuf:"varint,8,opt,name=gid,proto3" json:"gid,omitempty"`
	User                 string   `protobuf:"bytes,9,opt,name=user,proto3" json:"user,omitempty"`
	Group                string   `protobuf:"bytes,10,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7183a11194efb25, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_Normal
}

func (m *File) GetSymlink() string {
	if m != nil {
		return m.Symlink
	}
	return ""
}

func (m *File) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *File) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *File) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *File) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *File) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type SyncRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7183a11194efb25, []int{1}
}

func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (m *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(m, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

func (m *SyncRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type SyncResponse struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncResponse) Reset()         { *m = SyncResponse{} }
func (m *SyncResponse) String() string { return proto.CompactTextString(m) }
func (*SyncResponse) ProtoMessage()    {}
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7183a11194efb25, []int{2}
}

func (m *SyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResponse.Unmarshal(m, b)
}
func (m *SyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResponse.Marshal(b, m, deterministic)
}
func (m *SyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResponse.Merge(m, src)
}
func (m *SyncResponse) XXX_Size() int {
	return xxx_messageInfo_SyncResponse.Size(m)
}
func (m *SyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResponse proto.InternalMessageInfo

func (m *SyncResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.Type", Type_name, Type_value)
	proto.RegisterType((*File)(nil), "protocol.File")
	proto.RegisterType((*SyncRequest)(nil), "protocol.SyncRequest")
	proto.RegisterType((*SyncResponse)(nil), "protocol.SyncResponse")
}

func init() { proto.RegisterFile("protocol/sync.proto", fileDescriptor_b7183a11194efb25) }

var fileDescriptor_b7183a11194efb25 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4e, 0xf3, 0x30,
	0x10, 0xc5, 0x3f, 0x37, 0xe9, 0xbf, 0xe9, 0xd7, 0x2a, 0x1a, 0x58, 0x8c, 0x58, 0x85, 0x88, 0x45,
	0xc4, 0x22, 0x48, 0xc0, 0x11, 0x10, 0x4b, 0x16, 0x29, 0x17, 0x28, 0xc9, 0xd0, 0x5a, 0x4d, 0xe2,
	0x60, 0x27, 0x0b, 0x73, 0x64, 0x4e, 0x81, 0x6c, 0x2b, 0x88, 0x05, 0xbb, 0xf7, 0x7e, 0x33, 0x7e,
	0xf6, 0x33, 0x5c, 0xf4, 0x5a, 0x0d, 0xaa, 0x52, 0xcd, 0x9d, 0xb1, 0x5d, 0x55, 0x78, 0x87, 0xab,
	0x09, 0x66, 0x5f, 0x02, 0xe2, 0x67, 0xd9, 0x30, 0x22, 0xc4, 0xfd, 0x61, 0x38, 0x91, 0x48, 0x45,
	0xbe, 0x2e, 0xbd, 0xc6, 0x2b, 0x58, 0x55, 0x27, 0xae, 0xce, 0x66, 0x6c, 0x69, 0xe6, 0xf9, 0x8f,
	0x77, 0xfb, 0x46, 0x7e, 0x32, 0x45, 0xa9, 0xc8, 0xa3, 0xd2, 0x6b, 0xcc, 0x20, 0x1e, 0x6c, 0xcf,
	0x14, 0xa7, 0x22, 0xdf, 0xdd, 0xef, 0x8a, 0xe9, 0x96, 0xe2, 0xd5, 0xf6, 0x5c, 0xfa, 0x19, 0x12,
	0x2c, 0x8d, 0x6d, 0x1b, 0xd9, 0x9d, 0x69, 0xee, 0x23, 0x27, 0xeb, 0x12, 0x5b, 0x55, 0x33, 0x2d,
	0x52, 0x91, 0x6f, 0x4b, 0xaf, 0x31, 0x81, 0x68, 0x94, 0x35, 0x2d, 0x3d, 0x72, 0xd2, 0x91, 0xa3,
	0xac, 0x69, 0x15, 0xc8, 0x51, 0xd6, 0xee, 0xdc, 0x68, 0x58, 0xd3, 0x3a, 0xbc, 0xdc, 0x69, 0xbc,
	0x84, 0xf9, 0x51, 0xab, 0xb1, 0x27, 0xf0, 0x30, 0x98, 0xec, 0x1a, 0x36, 0x7b, 0xdb, 0x55, 0x25,
	0x7f, 0x8c, 0x6c, 0x86, 0xbf, 0x2a, 0x67, 0x8f, 0xf0, 0x3f, 0xac, 0x98, 0x5e, 0x75, 0x86, 0xf1,
	0x06, 0xe6, 0xef, 0xb2, 0x61, 0x43, 0x22, 0x8d, 0xf2, 0xcd, 0xef, 0x4e, 0xee, 0xd7, 0xca, 0x30,
	0xbc, 0x2d, 0x20, 0x76, 0x15, 0x11, 0x60, 0xf1, 0xa2, 0x74, 0x7b, 0x68, 0x92, 0x7f, 0xb8, 0x85,
	0xf5, 0x93, 0xd4, 0x5c, 0x0d, 0x4a, 0xdb, 0x44, 0xe0, 0x06, 0x96, 0xfb, 0x50, 0x34, 0x99, 0xbd,
	0x2d, 0x7c, 0xca, 0xc3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0x18, 0x6c, 0xa8, 0x9d, 0x01,
	0x00, 0x00,
}
