basePath: /api
definitions:
  collector.Collector:
    properties:
      collectors:
        $ref: '#/definitions/collector.Collectors'
        type: object
      index:
        type: integer
      jobID:
        type: string
      lock:
        type: string
      stages:
        items:
          $ref: '#/definitions/collector.Stage'
        type: array
    type: object
  collector.Collectors:
    properties:
      collectors:
        type: object
      lock:
        type: string
    type: object
  collector.Progress:
    properties:
      lock:
        type: string
      max:
        type: integer
      total:
        type: integer
    type: object
  collector.Stage:
    properties:
      col:
        $ref: '#/definitions/collector.Collector'
        type: object
      lock:
        type: string
      max:
        type: integer
      messages:
        items:
          $ref: '#/definitions/collector.StageMessage'
        type: array
      name:
        type: string
      percentage:
        type: number
      progress:
        $ref: '#/definitions/collector.Progress'
        type: object
      total:
        type: integer
    type: object
  collector.StageMessage:
    properties:
      index:
        type: integer
      level:
        type: string
      message:
        type: string
      timestamp:
        type: string
    type: object
  controller.BulkDeleteReq:
    properties:
      names:
        items:
          type: string
        type: array
    type: object
  controller.BulkSyncReq:
    properties:
      defs:
        items:
          type: string
        type: array
    type: object
  controller.History:
    properties:
      created_at:
        type: string
      id:
        type: string
      job:
        $ref: '#/definitions/job.FileSyncJob'
        type: object
      job_id:
        type: string
      name:
        type: string
      output:
        $ref: '#/definitions/collector.Collector'
        type: object
      status:
        type: string
    type: object
  controller.JobStatus:
    properties:
      definition_name:
        type: string
      id:
        type: string
      status:
        type: string
    type: object
  controller.WelcomeMessage:
    properties:
      version:
        type: string
    type: object
  job.FileSyncJob:
    properties:
      cc:
        type: string
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      payload:
        $ref: '#/definitions/meta.FileSyncGroup'
        type: object
      syncSetting:
        $ref: '#/definitions/meta.GlobalFileSyncSetting'
        type: object
    type: object
  meta.File:
    properties:
      after:
        items:
          $ref: '#/definitions/meta.SyncAction'
        type: array
      before:
        items:
          $ref: '#/definitions/meta.SyncAction'
        type: array
      dest:
        type: string
      error:
        items:
          $ref: '#/definitions/meta.SyncAction'
        type: array
      ignores:
        items:
          type: string
        type: array
      skip_when_error:
        type: boolean
      src:
        type: string
    type: object
  meta.FileSyncGroup:
    properties:
      Files:
        items:
          $ref: '#/definitions/meta.File'
        type: array
      after:
        items:
          $ref: '#/definitions/meta.SyncAction'
        type: array
      before:
        items:
          $ref: '#/definitions/meta.SyncAction'
        type: array
      error:
        items:
          $ref: '#/definitions/meta.SyncAction'
        type: array
      from:
        type: string
      name:
        type: string
      rules:
        items:
          $ref: '#/definitions/meta.Rule'
        type: array
      token:
        type: string
    type: object
  meta.GlobalFileSyncSetting:
    properties:
      after:
        items:
          $ref: '#/definitions/meta.SyncAction'
        type: array
      before:
        items:
          $ref: '#/definitions/meta.SyncAction'
        type: array
      errors:
        items:
          $ref: '#/definitions/meta.SyncAction'
        type: array
      from:
        type: string
      token:
        type: string
    type: object
  meta.Rule:
    properties:
      action:
        type: string
      command:
        type: string
      match:
        type: string
      replace:
        type: string
      src:
        type: string
    type: object
  meta.SyncAction:
    properties:
      action:
        type: string
      body:
        description: '--- dingding ---'
        type: string
      command:
        description: '--- command ---'
        type: string
      parse_template:
        type: boolean
      token:
        type: string
      when:
        type: string
    type: object
host: localhost:8819
info:
  contact:
    email: mylxsw@aicode.cc
    name: mylxsw
    url: https://github.com/mylxsw/sync
  description: 文件同步服务
  license:
    name: MIT
    url: https://raw.githubusercontent.com/mylxsw/sync/master/LICENSE
  title: Sync API
  version: "1.0"
paths:
  /:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.WelcomeMessage'
      summary: 欢迎页面，API版本信息
  /failed-jobs/:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/job.FileSyncJob'
            type: array
      summary: 返回失败的所有任务
      tags:
      - FailedJobs
  /failed-jobs/{id}/:
    delete:
      parameters:
      - description: 删除失败的 Job ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/job.FileSyncJob'
      summary: 删除失败的任务
      tags:
      - FailedJobs
    put:
      parameters:
      - description: 要重试的 Job ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/job.FileSyncJob'
      summary: 重试失败的任务
      tags:
      - FailedJobs
  /histories/:
    get:
      parameters:
      - description: 返回记录数目
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controller.History'
            type: array
      summary: 查询最近的文件同步记录
      tags:
      - Histories
  /histories/{id}/:
    get:
      parameters:
      - description: 记录ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.History'
      summary: 返回指定ID的历史纪录详情
      tags:
      - Histories
  /jobs-bulk/:
    post:
      parameters:
      - description: 同步定义列表
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.BulkSyncReq'
          type: object
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controller.JobStatus'
            type: array
      summary: 批量发起文件同步
      tags:
      - Jobs
  /jobs/:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/job.FileSyncJob'
            type: array
      summary: 返回队列中所有任务
      tags:
      - Jobs
    post:
      parameters:
      - description: 同步定义名称
        in: query
        name: def
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JobStatus'
      summary: 发起文件同步任务
      tags:
      - Jobs
  /jobs/{id}/:
    get:
      parameters:
      - description: Job ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.JobStatus'
      summary: 查询文件同步任务执行状态
      tags:
      - Jobs
  /running-jobs/{id}/:
    get:
      summary: 运行中的任务状态，基于websocket
      tags:
      - RunningJobs
  /sync-bulk/:
    delete:
      parameters:
      - description: 定义名称列表
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.BulkDeleteReq'
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 批量删除同步定义
      tags:
      - Sync
  /sync/:
    get:
      parameters:
      - description: 输出格式：yaml/json
        in: query
        name: format
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/meta.FileSyncGroup'
            type: array
      summary: 查询所有文件同步定义
      tags:
      - Sync
    post:
      consumes:
      - application/json
      parameters:
      - description: 文件同步定义
        in: body
        name: def
        required: true
        schema:
          items:
            $ref: '#/definitions/meta.FileSyncGroup'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/meta.FileSyncGroup'
            type: array
      summary: 更新文件同步定义
      tags:
      - Sync
  /sync/{name}/:
    delete:
      parameters:
      - description: 定义名称
        in: path
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除单个文件同步定义
      tags:
      - Sync
    get:
      parameters:
      - description: 定义名称
        in: path
        name: name
        required: true
        type: string
      - description: 输出格式：yaml/json
        in: query
        name: format
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/meta.FileSyncGroup'
            type: array
      summary: 查询单个文件同步定义
      tags:
      - Sync
swagger: "2.0"
